### ISSUE TITLE
Open data field for whether charities have changed their name?

### ISSUE THREAD

**Issue by janoschortmann** [ajah/nonprofitknowledge#7]

**Comment by mlenczner** [comment]
After going through the T3010 datasets, we couldn't find a field for alternate charity names. However, there may be an alternate way to get this data. 

On the CRA's website, under their charity section, each charity has its own profile. If you select the "detailed view" on a specifica year, there is a section named " Basic information sheet".  When you expand it, there is an optional field called: "Names the charity is known by other than its registered name" (https://apps.cra-arc.gc.ca/ebci/hacc/srch/pub/t3010/v23/t3010ovrvw). If we wanted that data, we could scrape it from there. 

Before starting that work, it might be useful to talk to Ajah, since they already have a scraper written for those pages.
